In [31]:
import pandas as pd
import numpy as np
# 1. Wczytać zbiór danych z pliku movie_new.csv do ramki movie_new. Przy użyciu parametru names funkcji read_csv nadać następujące nazwy kolumnom: color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes.
column_names = ['color', 'director_name', 'num_critic_for_reviews', 'duration', 'director_facebook_likes', 'actor_3_facebook_likes'
                , 'actor_2_name', 'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name', 'movie_title', 'num_voted_users', 'cast_total_facebook_likes'
                , 'actor_3_name', 'facenumber_in_poster', 'plot_keywords', 'movie_imdb_link', 'num_user_for_reviews', 'language', 'country', 'content_rating'
                , 'budget', 'title_year', 'actor_2_facebook_likes', 'imdb_score', 'aspect_ratio', 'movie_facebook_likes']

movie_new = pd.read_csv('../WIED/movie_new.csv', names=column_names, sep=',', header=0)
movie_new.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [17]:
# 2. Utworzyć ramkę movie_num, w której będą zawarte jedynie kolumny z wartościami typu numerycznego.
movie_num = movie_new.select_dtypes(include= ['number'])
movie_num.head(5)

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,723.0,178.0,0.0,855.0,1000.0,760505847.0,886204,4834,0.0,3054.0,237000000.0,2009.0,936.0,7.9,1.78,33000
1,302.0,169.0,563.0,1000.0,40000.0,309404152.0,471220,48350,0.0,1238.0,300000000.0,2007.0,5000.0,7.1,2.35,0
2,602.0,148.0,0.0,161.0,11000.0,200074175.0,275868,11700,1.0,994.0,245000000.0,2015.0,393.0,6.8,2.35,85000
3,813.0,164.0,22000.0,23000.0,27000.0,448130642.0,1144337,106759,0.0,2701.0,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,NaN,131.0,NaN,131.0,NaN,8,143,0.0,NaN,NaN,NaN,12.0,7.1,NaN,0

In [19]:
# 3. Wypełnić brakujące wartości w ramce movie_num średnią arytmetyczną wyznaczoną dla każdej kolumny z osobna. 
means = movie_num.describe().loc['mean']

#movie_num = movie_num.fillna(means)
movie_num.fillna(means, inplace=True)
print(means)
movie_num.head(5)

num_critic_for_reviews       1.379889e+02
duration                     1.070908e+02
director_facebook_likes      6.910145e+02
actor_3_facebook_likes       6.312763e+02
actor_1_facebook_likes       6.494488e+03
gross                        4.764451e+07
num_voted_users              8.264492e+04
cast_total_facebook_likes    9.579816e+03
facenumber_in_poster         1.377320e+00
num_user_for_reviews         2.676688e+02
budget                       3.654749e+07
title_year                   2.002448e+03
actor_2_facebook_likes       1.621924e+03
imdb_score                   6.437429e+00
aspect_ratio                 2.222349e+00
movie_facebook_likes         7.348294e+03
Name: mean, dtype: float64

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,723.000000,178.000000,0.0,855.000000,1000.0,7.605058e+08,886204,4834,0.0,3054.000000,2.370000e+08,2009.000000,936.0,7.9,1.780000,33000
1,302.000000,169.000000,563.0,1000.000000,40000.0,3.094042e+08,471220,48350,0.0,1238.000000,3.000000e+08,2007.000000,5000.0,7.1,2.350000,0
2,602.000000,148.000000,0.0,161.000000,11000.0,2.000742e+08,275868,11700,1.0,994.000000,2.450000e+08,2015.000000,393.0,6.8,2.350000,85000
3,813.000000,164.000000,22000.0,23000.000000,27000.0,4.481306e+08,1144337,106759,0.0,2701.000000,2.500000e+08,2012.000000,23000.0,8.5,2.350000,164000
4,137.988905,107.090798,131.0,631.276313,131.0,4.764451e+07,8,143,0.0,267.668846,3.654749e+07,2002.447609,12.0,7.1,2.222349,0

In [118]:
# 4. Znaleźć kolumnę w ramce movie_num, której wartości mają największe odchylenie standardowe.
column_std = movie_num.std()
column_with_max_std = column_std.idxmax()
print(f' kolumna z najwyzszym std: {column_with_max_std}\n std dla wszystkich kolumn: \n{column_std}')

 kolumna z najwyzszym std: budget
 std dla wszystkich kolumn:
num_critic_for_reviews       1.196385e+02
duration                     2.524740e+01
director_facebook_likes      2.803404e+03
actor_3_facebook_likes       1.622066e+03
actor_1_facebook_likes       1.509623e+04
gross                        6.118001e+07
num_voted_users              1.383222e+05
cast_total_facebook_likes    1.816432e+04
facenumber_in_poster         2.021148e+00
num_user_for_reviews         3.721373e+02
budget                       9.517914e+07
title_year                   1.231895e+01
actor_2_facebook_likes       4.005991e+03
imdb_score                   1.127802e+00
aspect_ratio                 1.355615e+00
movie_facebook_likes         1.920602e+04
dtype: float64

In [20]:
# 5. Zastąpić kolumny numeryczne w ramce movie_new nowymi kolumnami z ramki movie_num.
movie_new.update(movie_num)
movie_new.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.000000,178.000000,0.0,855.000000,Joel David Moore,1000.0,7.605058e+08,Action|Adventure|Fantasy|Sci-Fi,...,3054.000000,English,USA,PG-13,2.370000e+08,2009.000000,936.0,7.9,1.780000,33000
1,Color,Gore Verbinski,302.000000,169.000000,563.0,1000.000000,Orlando Bloom,40000.0,3.094042e+08,Action|Adventure|Fantasy,...,1238.000000,English,USA,PG-13,3.000000e+08,2007.000000,5000.0,7.1,2.350000,0
2,Color,Sam Mendes,602.000000,148.000000,0.0,161.000000,Rory Kinnear,11000.0,2.000742e+08,Action|Adventure|Thriller,...,994.000000,English,UK,PG-13,2.450000e+08,2015.000000,393.0,6.8,2.350000,85000
3,Color,Christopher Nolan,813.000000,164.000000,22000.0,23000.000000,Christian Bale,27000.0,4.481306e+08,Action|Thriller,...,2701.000000,English,USA,PG-13,2.500000e+08,2012.000000,23000.0,8.5,2.350000,164000
4,NaN,Doug Walker,137.988905,107.090798,131.0,631.276313,Rob Walker,131.0,4.764451e+07,Documentary,...,267.668846,NaN,NaN,NaN,3.654749e+07,2002.447609,12.0,7.1,2.222349,0

In [21]:
# 6. Zastąpić wszystkie wartości wybrakowane w ramce movie_new za pomocą pierwszej wartości występującej w kolumnie.
movie_new.fillna(method='ffill', axis=0, inplace=True)
movie_new.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.000000,178.000000,0.0,855.000000,Joel David Moore,1000.0,7.605058e+08,Action|Adventure|Fantasy|Sci-Fi,...,3054.000000,English,USA,PG-13,2.370000e+08,2009.000000,936.0,7.9,1.780000,33000
1,Color,Gore Verbinski,302.000000,169.000000,563.0,1000.000000,Orlando Bloom,40000.0,3.094042e+08,Action|Adventure|Fantasy,...,1238.000000,English,USA,PG-13,3.000000e+08,2007.000000,5000.0,7.1,2.350000,0
2,Color,Sam Mendes,602.000000,148.000000,0.0,161.000000,Rory Kinnear,11000.0,2.000742e+08,Action|Adventure|Thriller,...,994.000000,English,UK,PG-13,2.450000e+08,2015.000000,393.0,6.8,2.350000,85000
3,Color,Christopher Nolan,813.000000,164.000000,22000.0,23000.000000,Christian Bale,27000.0,4.481306e+08,Action|Thriller,...,2701.000000,English,USA,PG-13,2.500000e+08,2012.000000,23000.0,8.5,2.350000,164000
4,Color,Doug Walker,137.988905,107.090798,131.0,631.276313,Rob Walker,131.0,4.764451e+07,Documentary,...,267.668846,English,USA,PG-13,3.654749e+07,2002.447609,12.0,7.1,2.222349,0

In [23]:
# 7. Nadać nowe indeksy wierszom w ramce movie_new według następującego schematu: [imie i nazwisko rezysera] - [tytul filmu].
movie_new['new_index'] = movie_new['director_name'] + ' - ' + movie_new['movie_title']
movie_new.set_index('new_index', inplace=True)
movie_new.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
new_index,,,,,,,,,,,,,,,,,,,,,
James Cameron - Avatar,Color,James Cameron,723.000000,178.000000,0.0,855.000000,Joel David Moore,1000.0,7.605058e+08,Action|Adventure|Fantasy|Sci-Fi,...,3054.000000,English,USA,PG-13,2.370000e+08,2009.000000,936.0,7.9,1.780000,33000
Gore Verbinski - Pirates of the Caribbean: At World's End,Color,Gore Verbinski,302.000000,169.000000,563.0,1000.000000,Orlando Bloom,40000.0,3.094042e+08,Action|Adventure|Fantasy,...,1238.000000,English,USA,PG-13,3.000000e+08,2007.000000,5000.0,7.1,2.350000,0
Sam Mendes - Spectre,Color,Sam Mendes,602.000000,148.000000,0.0,161.000000,Rory Kinnear,11000.0,2.000742e+08,Action|Adventure|Thriller,...,994.000000,English,UK,PG-13,2.450000e+08,2015.000000,393.0,6.8,2.350000,85000
Christopher Nolan - The Dark Knight Rises,Color,Christopher Nolan,813.000000,164.000000,22000.0,23000.000000,Christian Bale,27000.0,4.481306e+08,Action|Thriller,...,2701.000000,English,USA,PG-13,2.500000e+08,2012.000000,23000.0,8.5,2.350000,164000
Doug Walker - Star Wars: Episode VII - The Force Awakens,Color,Doug Walker,137.988905,107.090798,131.0,631.276313,Rob Walker,131.0,4.764451e+07,Documentary,...,267.668846,English,USA,PG-13,3.654749e+07,2002.447609,12.0,7.1,2.222349,0

In [24]:
# 8. Zwiększyć wartość kolumny imdb_score każdego filmu w ramce movie_new o 1.
movie_new['imdb_score'] = movie_new['imdb_score'] + 1
movie_new.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
new_index,,,,,,,,,,,,,,,,,,,,,
James Cameron - Avatar,Color,James Cameron,723.000000,178.000000,0.0,855.000000,Joel David Moore,1000.0,7.605058e+08,Action|Adventure|Fantasy|Sci-Fi,...,3054.000000,English,USA,PG-13,2.370000e+08,2009.000000,936.0,8.9,1.780000,33000
Gore Verbinski - Pirates of the Caribbean: At World's End,Color,Gore Verbinski,302.000000,169.000000,563.0,1000.000000,Orlando Bloom,40000.0,3.094042e+08,Action|Adventure|Fantasy,...,1238.000000,English,USA,PG-13,3.000000e+08,2007.000000,5000.0,8.1,2.350000,0
Sam Mendes - Spectre,Color,Sam Mendes,602.000000,148.000000,0.0,161.000000,Rory Kinnear,11000.0,2.000742e+08,Action|Adventure|Thriller,...,994.000000,English,UK,PG-13,2.450000e+08,2015.000000,393.0,7.8,2.350000,85000
Christopher Nolan - The Dark Knight Rises,Color,Christopher Nolan,813.000000,164.000000,22000.0,23000.000000,Christian Bale,27000.0,4.481306e+08,Action|Thriller,...,2701.000000,English,USA,PG-13,2.500000e+08,2012.000000,23000.0,9.5,2.350000,164000
Doug Walker - Star Wars: Episode VII - The Force Awakens,Color,Doug Walker,137.988905,107.090798,131.0,631.276313,Rob Walker,131.0,4.764451e+07,Documentary,...,267.668846,English,USA,PG-13,3.654749e+07,2002.447609,12.0,8.1,2.222349,0

In [25]:
# 9. Zmienić nazwy wszystkich kolumn w ramce movie_new w taki sposób aby zlikwidować wszystkie znaki _ oraz pierwsze litery wszystkich słów w nazwach były wielkie.
movie_new.rename(columns=lambda x: x.replace('_', ' ').title(), inplace=True)
movie_new.head()

,Color,Director Name,Num Critic For Reviews,Duration,Director Facebook Likes,Actor 3 Facebook Likes,Actor 2 Name,Actor 1 Facebook Likes,Gross,Genres,...,Num User For Reviews,Language,Country,Content Rating,Budget,Title Year,Actor 2 Facebook Likes,Imdb Score,Aspect Ratio,Movie Facebook Likes
new_index,,,,,,,,,,,,,,,,,,,,,
James Cameron - Avatar,Color,James Cameron,723.000000,178.000000,0.0,855.000000,Joel David Moore,1000.0,7.605058e+08,Action|Adventure|Fantasy|Sci-Fi,...,3054.000000,English,USA,PG-13,2.370000e+08,2009.000000,936.0,8.9,1.780000,33000
Gore Verbinski - Pirates of the Caribbean: At World's End,Color,Gore Verbinski,302.000000,169.000000,563.0,1000.000000,Orlando Bloom,40000.0,3.094042e+08,Action|Adventure|Fantasy,...,1238.000000,English,USA,PG-13,3.000000e+08,2007.000000,5000.0,8.1,2.350000,0
Sam Mendes - Spectre,Color,Sam Mendes,602.000000,148.000000,0.0,161.000000,Rory Kinnear,11000.0,2.000742e+08,Action|Adventure|Thriller,...,994.000000,English,UK,PG-13,2.450000e+08,2015.000000,393.0,7.8,2.350000,85000
Christopher Nolan - The Dark Knight Rises,Color,Christopher Nolan,813.000000,164.000000,22000.0,23000.000000,Christian Bale,27000.0,4.481306e+08,Action|Thriller,...,2701.000000,English,USA,PG-13,2.500000e+08,2012.000000,23000.0,9.5,2.350000,164000
Doug Walker - Star Wars: Episode VII - The Force Awakens,Color,Doug Walker,137.988905,107.090798,131.0,631.276313,Rob Walker,131.0,4.764451e+07,Documentary,...,267.668846,English,USA,PG-13,3.654749e+07,2002.447609,12.0,8.1,2.222349,0

In [28]:
# 10. Utworzyć ramkę movie_random, w której zostaną wybrane wiersze o losowej ilości w zakresie pozycji [start, end], gdzie start i end będą liczbami pseudolosowymi.

start = np.random.randint(0, len(movie_new))
end = np.random.randint(start, len(movie_new))

# Sample rows within the specified range
movie_random = movie_new.iloc[start:end+1].copy()
print(f'start: {start}, end: {end}')
movie_random.describe()

start: 727, end: 4483

,Num Critic For Reviews,Duration,Director Facebook Likes,Actor 3 Facebook Likes,Actor 1 Facebook Likes,Gross,Num Voted Users,Cast Total Facebook Likes,Facenumber In Poster,Num User For Reviews,Budget,Title Year,Actor 2 Facebook Likes,Imdb Score,Aspect Ratio,Movie Facebook Likes
count,3757.000000,3757.000000,3757.000000,3757.000000,3757.000000,3.757000e+03,3.757000e+03,3757.000000,3757.000000,3757.000000,3.757000e+03,3757.000000,3757.000000,3757.000000,3757.000000,3757.000000
mean,125.887608,106.623297,629.847019,532.239563,6045.570662,3.543131e+07,6.697197e+04,8744.513442,1.431034,224.119960,2.683090e+07,2001.783175,1385.959440,7.420575,2.182940,5788.700293
std,104.246996,24.852263,2628.527099,1212.116884,15094.451184,3.874105e+07,1.117451e+05,17488.234678,2.087877,271.270947,1.015764e+08,12.408526,3762.822031,1.131022,1.188938,14670.787132
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,6.000000e+00,0.000000,0.000000,1.000000,1.300000e+04,1927.000000,0.000000,2.600000,1.180000,0.000000
25%,49.000000,94.000000,9.000000,140.000000,629.000000,6.852144e+06,9.007000e+03,1456.000000,0.000000,66.000000,8.000000e+06,1998.000000,292.000000,6.800000,1.850000,0.000000
50%,100.000000,103.000000,50.000000,364.000000,973.000000,2.832813e+07,2.962100e+04,3007.000000,1.000000,144.000000,2.000000e+07,2004.000000,591.000000,7.500000,2.222349,161.000000
75%,172.000000,116.000000,189.000000,616.000000,11000.000000,4.764451e+07,7.679100e+04,12566.000000,2.000000,279.000000,3.654749e+07,2010.000000,889.000000,8.200000,2.350000,1000.000000
max,676.000000,511.000000,23000.000000,19000.000000,640000.000000,4.609357e+08,1.689764e+06,656730.000000,43.000000,4144.000000,4.200000e+09,2016.000000,137000.000000,10.500000,16.000000,165000.000000

In [30]:
# 11. Zwiększyć wartości każdej kolumny numerycznej w ramce movie_random o wartość pseudolosową (po jednej wartości na kolumnę).
numeric_columns = movie_random.select_dtypes(include=['number'])

def add_random_value(column):
    return column + np.random.normal(8,10)

movie_random[numeric_columns.columns] = numeric_columns.apply(add_random_value)

movie_random.head()

,Color,Director Name,Num Critic For Reviews,Duration,Director Facebook Likes,Actor 3 Facebook Likes,Actor 2 Name,Actor 1 Facebook Likes,Gross,Genres,...,Num User For Reviews,Language,Country,Content Rating,Budget,Title Year,Actor 2 Facebook Likes,Imdb Score,Aspect Ratio,Movie Facebook Likes
new_index,,,,,,,,,,,,,,,,,,,,,
Robert Redford - The Horse Whisperer,Color,Robert Redford,90.58723,197.222433,-3.738811,386.093409,Kristin Scott Thomas,19021.98559,7.537075e+07,Drama|Romance|Western,...,279.355395,English,USA,PG-13,6.000004e+07,2020.232475,1027.110789,13.305394,28.057465,16.594184
Michael Mann - Collateral,Color,Michael Mann,293.58723,147.222433,-3.738811,686.093409,Jada Pinkett Smith,10021.98559,1.000035e+08,Crime|Drama|Thriller,...,852.355395,English,USA,R,6.500004e+07,2026.232475,878.110789,14.405394,28.557465,16.594184
Chuck Russell - The Scorpion King,Color,Chuck Russell,161.58723,127.222433,51.261189,422.093409,Roger Rees,12021.98559,9.034166e+07,Action|Adventure|Fantasy|Thriller,...,448.355395,English,USA,PG-13,6.000004e+07,2024.232475,1027.110789,12.305394,28.557465,16.594184
Jay Russell - Ladder 49,Color,Jay Russell,119.58723,142.222433,9.261189,585.093409,Jay Hernandez,2021.98559,7.454075e+07,Action|Drama|Thriller,...,339.355395,English,USA,PG-13,5.500004e+07,2026.232475,1027.110789,13.305394,28.057465,16.594184
Christopher McQuarrie - Jack Reacher,Color,Christopher McQuarrie,381.58723,157.222433,184.261189,1006.093409,Robert Duvall,10021.98559,8.003363e+07,Action|Crime|Mystery|Thriller,...,464.355395,English,USA,PG-13,6.000004e+07,2034.232475,3027.110789,13.805394,28.557465,38016.594184